solved Task 3.1.2
Ivan-Sizov/Task-3.1.2 pull request #1
Opened 2023-06-02 11:45 UTC by wuller1

2023-06-02 15:05 UTC, pdasilem requested changes

2023-06-02 15:05 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controller/UserController.java
> +@RequestMapping("")
разделить контроллеры на admin и user
в реквест маппинге - админ и юзер

2023-06-02 15:05 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/dao/UserDAO.java
> +    User getUser(int id);
необязательно, но можно попробовать подключить springjpa. он проще и практика будет )

2023-06-02 15:05 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/User.java
> +    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
убрать eager

2023-06-02 15:05 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/service/UserService.java
> +public class UserService {
а где интерфейс/реализация?

2023-06-03 01:55 UTC, wuller1 commented on src/main/java/ru/itmentor/spring/boot_security/demo/model/User.java
> +    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
А почему нельзя использовать Eager? Нужно использовать Join в запросе?

2023-06-04 08:40 UTC, pdasilem approved these changes

2023-06-04 08:40 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/dao/UserDAO.java
> +    @Query("SELECT DISTINCT u FROM User u LEFT JOIN FETCH u.roles")
Distinct - не самый оптимальный оператор. И я не вижу необходимости использовать его в этом запросе.
Аналогично и в методе ниже

2023-06-11 09:18 UTC, merged